services:
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        environment:
            - POSTGRES_DB=diana
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./db/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d diana']
            interval: 5s
            timeout: 5s
            retries: 5

    migrate:
        image: postgres:15-alpine
        container_name: migrate
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - ./db/migrations:/migrations
            - ./db/migrate.sh:/migrate.sh
        environment:
            - PGHOST=postgres
            - PGPORT=5432
            - PGUSER=postgres
            - PGPASSWORD=admin
            - PGDATABASE=diana
            - MIGRATIONS_DIR=/migrations
        command: ['sh', '/migrate.sh']
        restart: 'no'

volumes:
    postgres_data:
