services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    ports:
      - "3000:3000"
    depends_on:
      - db

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.web
  #   container_name: web
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
