version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: diana_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diana_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  db_data: